name: 'Setup Python Poetry Just'
description: 'An action to setup Python, Poetry and Just plus install project dependencies.'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
  - uses: abatilo/actions-poetry@v3
    with:
      poetry-version: '1.8.3'
  - uses: actions/setup-python@v5
    with:
      python-version: '3.12'
      cache: 'poetry'
  - uses: extractions/setup-just@v2
  - name: install dependencies
    run: just install
    shell: bash
